### ISSUE TITLE
About single header

### ISSUE THREAD

**Issue by Teskann** [eliabieri/blnscpp#2]
Hi 😃

This project is presented as a single header API for BLNS. However it has not been the case anymore since I pushed my changes. We could imagine using a tool like [Quom](https://github.com/Viatorus/quom) to generate the header and release it using Github actions. However the header-only release would not include `blns.txt` as it is not in this repository anymore.

We have two choices :

- We could deliver the header with a fixed version of blns.txt (downloaded in a github pipeline). This would make the API usable even for people that don't use Cmake. However, as blns.txt version is fixed, we would have to release a new version of the project everytime the list is updated. The user would need to download the release everytime and frequently check for updates. Not very convenient, either for the user and for us.

- We could change the way the project is presented and stop delivering a single header for this.

In my opinion it is important to have an updated version of the list as vulnerabilities may be discovered frequently. The single header could be compromising for the security of the user's app. 

*NB : With CMake, the list is updated automatically when you run `cmake` from a clean directory.*

What do you think ?

**Comment by eliabieri** [comment]
Hi @Teskann,
thank you very much for taking the time to write down these considerations.  
I do agree that having an updated version of the list is very important.  
Since I'm not that involved any more with the project, I leave the rest of the decisions up to you.  
What do you think about me adding you as a maintainer?

**Comment by Teskann** [comment]
Hi @eliabieri,

Let's do this! Thank you very much for your confidence 😀

**Comment by eliabieri** [comment]
I just sent out an invitation!

**Comment by Teskann** [comment]
Hi @eliabieri, I updated the readme with some more documentation regarding this issue. We should update the repository description. I can't do it because I can't access the repository settings. I don't know if you can grant me the access, or make the changes yourself.

Cheers.

**Comment by eliabieri** [comment]
The updated documentation looks great! Thanks a lot for the contribution.  
I sadly don't seem to be able to give permissions to update the description.  
Would you mind just pasting the description text here, and I'll do the update?

**Comment by Teskann** [comment]
Sure. I think to something very simple:

>C++ API for the Big List of Naughty Strings

No emoji nor hyperlink there to make it more readable.

**Comment by eliabieri** [comment]
Done ✌🏼
